# =============================================
# Nomi Backend — Perfil PROD
# =============================================
spring:
  flyway:
    validate-on-migrate: true
  jpa:
    show-sql: false
  docker:
    compose:
      lifecycle-management: none

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    com.nomi.backend: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health,info
